tracer.property: "I am the default"
spring.jpa.database: "POSTGRESQL"
spring.datasource.platform: "postgres"
spring.jpa.show-sql: "true"
spring.database.driverClassName: "org.postgresql.Driver"
spring.database.url: "jdbc:postgresql://database:5432/redcabbage_local"
spring.datasource.username: "postgres"
spring.datasource.password: "p0stgr@s"
spring.datasaource.testWhileIdle: "true"
spring.datasource.validationquery: "SELECT 1"
spring.jpa.properties.hibernate.dialect: "org.hibernate.dialect.PostgreSQLDialect"